// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_audio_filter_biquad\Audio_Filter_IP_src_Data_Type_Conversion_Out.v
// Created: 2024-11-07 11:40:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Audio_Filter_IP_src_Data_Type_Conversion_Out
// Source Path: hdlcoder_audio_filter_biquad/Audio_Filter/Filter_block/Data_Type_Conversion_Out
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Audio_Filter_IP_src_Data_Type_Conversion_Out
          (In1,
           Out1);


  input   signed [23:0] In1;  // sfix24_En22
  output  [47:0] Out1;  // ufix48


  wire signed [23:0] Concatenation_out1 [0:1];  // sfix24_En22 [2]
  wire [23:0] Data_Type_Conversion1_out1 [0:1];  // ufix24 [2]
  wire [23:0] Data_Type_Conversion1_out1_0;  // ufix24
  wire [23:0] Data_Type_Conversion1_out1_1;  // ufix24
  wire [47:0] Bit_Concat_out1;  // ufix48


  assign Concatenation_out1[0] = In1;
  assign Concatenation_out1[1] = In1;

  genvar ii1;
  generate
    for(ii1 = 32'sd0; ii1 <= 32'sd1; ii1 = ii1 + 32'sd1) begin:Data_Type_Conversion1_out1_gen
      assign Data_Type_Conversion1_out1[ii1] = Concatenation_out1[ii1];
    end
  endgenerate
  assign Data_Type_Conversion1_out1_0 = Data_Type_Conversion1_out1[0];
  assign Data_Type_Conversion1_out1_1 = Data_Type_Conversion1_out1[1];

  assign Bit_Concat_out1 = {Data_Type_Conversion1_out1_0, Data_Type_Conversion1_out1_1};
  assign Out1 = Bit_Concat_out1;

endmodule  // Audio_Filter_IP_src_Data_Type_Conversion_Out

