// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_audio_filter_biquad\Audio_Filter_IP_src_Control_Logic_To_Enable_Filters.v
// Created: 2024-11-07 11:40:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Audio_Filter_IP_src_Control_Logic_To_Enable_Filters
// Source Path: hdlcoder_audio_filter_biquad/Audio_Filter/Control_Logic_To_Enable_Filters
// Hierarchy Level: 1
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Audio_Filter_IP_src_Control_Logic_To_Enable_Filters
          (In1,
           Pass_Through,
           BiQuad_LPF,
           BiQuad_BPF,
           BiQuad_HPF);


  input   [7:0] In1;  // uint8
  output  Pass_Through;
  output  BiQuad_LPF;
  output  BiQuad_BPF;
  output  BiQuad_HPF;


  wire No_Filter_out1;
  wire LP_en_out1;
  wire BP_en_out1;
  wire HP_en_out1;


  assign No_Filter_out1 = In1 == 8'b00000000;
  assign Pass_Through = No_Filter_out1;

  assign LP_en_out1 = In1 == 8'b00000001;
  assign BiQuad_LPF = LP_en_out1;

  assign BP_en_out1 = In1 == 8'b00000010;
  assign BiQuad_BPF = BP_en_out1;

  assign HP_en_out1 = In1 == 8'b00000011;
  assign BiQuad_HPF = HP_en_out1;

endmodule  // Audio_Filter_IP_src_Control_Logic_To_Enable_Filters

