// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_audio_filter_biquad\Audio_Filter_IP_src_BiQuad_HPF.v
// Created: 2024-11-07 11:40:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Audio_Filter_IP_src_BiQuad_HPF
// Source Path: hdlcoder_audio_filter_biquad/Audio_Filter/Filter_block/BiQuad_HPF 
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Audio_Filter_IP_src_BiQuad_HPF
          (clk,
           reset,
           enb,
           In1,
           Enable,
           Out1);


  input   clk;
  input   reset;
  input   enb;
  input   signed [23:0] In1;  // sfix24_En22
  input   Enable;
  output  signed [23:0] Out1;  // sfix24_En22


  reg  [19:0] delayMatch_reg;  // ufix1 [20]
  wire Enable_out2;
  wire signed [23:0] Biquad_Filter_HPF_out1;  // sfix24_En22
  wire signed [23:0] Biquad_Filter_HPF_out1_bypass;  // sfix24_En22
  reg signed [23:0] Biquad_Filter_HPF_out1_last_value;  // sfix24_En22


  always @(posedge clk)
    begin : delayMatch_process
      if (reset == 1'b1) begin
        delayMatch_reg <= {20{1'b0}};
      end
      else begin
        if (enb) begin
          delayMatch_reg[0] <= Enable;
          delayMatch_reg[32'sd19:32'sd1] <= delayMatch_reg[32'sd18:32'sd0];
        end
      end
    end

  assign Enable_out2 = delayMatch_reg[19];

  Audio_Filter_IP_src_Biquad_Filter_HPF u_Biquad_Filter_HPF (.clk(clk),
                                                             .reset(reset),
                                                             .enb(enb),
                                                             .Biquad_Filter_HPF_In(In1),  // sfix24_En22
                                                             .Enable_out2(Enable),
                                                             .Biquad_Filter_HPF_out(Biquad_Filter_HPF_out1)  // sfix24_En22
                                                             );
  always @(posedge clk)
    begin : Out1_bypass_process
      if (reset == 1'b1) begin
        Biquad_Filter_HPF_out1_last_value <= 24'sb000000000000000000000000;
      end
      else begin
        if (enb) begin
          Biquad_Filter_HPF_out1_last_value <= Biquad_Filter_HPF_out1_bypass;
        end
      end
    end

  assign Biquad_Filter_HPF_out1_bypass = (Enable_out2 == 1'b0 ? Biquad_Filter_HPF_out1_last_value :
              Biquad_Filter_HPF_out1);

  assign Out1 = Biquad_Filter_HPF_out1_bypass;

endmodule  // Audio_Filter_IP_src_BiQuad_HPF

