// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_audio_filter_biquad\Audio_Filter_IP_dut.v
// Created: 2024-11-07 11:08:52
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Audio_Filter_IP_dut
// Source Path: Audio_Filter_IP/Audio_Filter_IP_dut
// Hierarchy Level: 1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Audio_Filter_IP_dut
          (clk,
           reset,
           dut_enable,
           Data_in,
           Valid_in,
           Filter_select,
           ce_out,
           Data_out,
           Valid_out,
           Pass_through_LED,
           BiQuad_LPF_LED,
           Biquad_BPF_LED,
           BiQuad_HPF_LED);


  input   clk;
  input   reset;
  input   dut_enable;  // ufix1
  input   [47:0] Data_in;  // ufix48
  input   Valid_in;  // ufix1
  input   [7:0] Filter_select;  // ufix8
  output  ce_out;  // ufix1
  output  [47:0] Data_out;  // ufix48
  output  Valid_out;  // ufix1
  output  Pass_through_LED;  // ufix1
  output  BiQuad_LPF_LED;  // ufix1
  output  Biquad_BPF_LED;  // ufix1
  output  BiQuad_HPF_LED;  // ufix1


  wire enb;
  wire ce_out_sig;  // ufix1
  wire [47:0] Data_out_sig;  // ufix48
  wire Valid_out_sig;  // ufix1
  wire Pass_through_LED_sig;  // ufix1
  wire BiQuad_LPF_LED_sig;  // ufix1
  wire Biquad_BPF_LED_sig;  // ufix1
  wire BiQuad_HPF_LED_sig;  // ufix1


  assign enb = dut_enable;

  Audio_Filter_IP_src_Audio_Filter u_Audio_Filter_IP_src_Audio_Filter (.clk(clk),
                                                                       .clk_enable(enb),
                                                                       .reset(reset),
                                                                       .Data_in(Data_in),  // ufix48
                                                                       .Valid_in(Valid_in),  // ufix1
                                                                       .Filter_select(Filter_select),  // ufix8
                                                                       .ce_out(ce_out_sig),  // ufix1
                                                                       .Data_out(Data_out_sig),  // ufix48
                                                                       .Valid_out(Valid_out_sig),  // ufix1
                                                                       .Pass_through_LED(Pass_through_LED_sig),  // ufix1
                                                                       .BiQuad_LPF_LED(BiQuad_LPF_LED_sig),  // ufix1
                                                                       .Biquad_BPF_LED(Biquad_BPF_LED_sig),  // ufix1
                                                                       .BiQuad_HPF_LED(BiQuad_HPF_LED_sig)  // ufix1
                                                                       );

  assign ce_out = ce_out_sig;

  assign Data_out = Data_out_sig;

  assign Valid_out = Valid_out_sig;

  assign Pass_through_LED = Pass_through_LED_sig;

  assign BiQuad_LPF_LED = BiQuad_LPF_LED_sig;

  assign Biquad_BPF_LED = Biquad_BPF_LED_sig;

  assign BiQuad_HPF_LED = BiQuad_HPF_LED_sig;

endmodule  // Audio_Filter_IP_dut

