// -------------------------------------------------------------
// 
// File Name: hdl_prj\hdlsrc\hdlcoder_audio_filter_biquad\Audio_Filter_IP_src_Data_Type_Conversion_In.v
// Created: 2024-11-07 11:40:50
// 
// Generated by MATLAB 24.2, HDL Coder 24.2, and Simulink 24.2
// 
// -------------------------------------------------------------


// -------------------------------------------------------------
// 
// Module: Audio_Filter_IP_src_Data_Type_Conversion_In
// Source Path: hdlcoder_audio_filter_biquad/Audio_Filter/Filter_block/Data_Type_Conversion_In
// Hierarchy Level: 2
// Model version: 10.1
// 
// -------------------------------------------------------------

`timescale 1 ns / 1 ns

module Audio_Filter_IP_src_Data_Type_Conversion_In
          (In1,
           Out1);


  input   [47:0] In1;  // ufix48
  output  signed [23:0] Out1;  // sfix24_En22


  wire [23:0] Bit_Slice_out1;  // ufix24
  wire [23:0] Bit_Slice1_out1;  // ufix24
  wire [23:0] Mux_out1 [0:1];  // ufix24 [2]
  wire signed [23:0] Data_Type_Conversion_out1 [0:1];  // sfix24_En22 [2]
  wire signed [23:0] Bit_Shift_out1 [0:1];  // sfix24_En22 [2]
  wire signed [23:0] Bit_Shift_out1_0;  // sfix24_En22
  wire signed [23:0] Bit_Shift_out1_1;  // sfix24_En22
  wire signed [23:0] Sum_out1;  // sfix24_En22


  assign Bit_Slice_out1 = In1[47:24];
  assign Bit_Slice1_out1 = In1[23:0];
  assign Mux_out1[0] = Bit_Slice_out1;
  assign Mux_out1[1] = Bit_Slice1_out1;

  genvar ii2;
  generate
    for(ii2 = 32'sd0; ii2 <= 32'sd1; ii2 = ii2 + 32'sd1) begin:Data_Type_Conversion_out1_gen
      assign Data_Type_Conversion_out1[ii2] = Mux_out1[ii2];
    end
  endgenerate

  genvar ii11;
  generate
    for(ii11 = 32'sd0; ii11 <= 32'sd1; ii11 = ii11 + 32'sd1) begin:Bit_Shift_out1_gen
      assign Bit_Shift_out1[ii11] = Data_Type_Conversion_out1[ii11] >>> 8'd1;
    end
  endgenerate
  assign Bit_Shift_out1_0 = Bit_Shift_out1[0];
  assign Bit_Shift_out1_1 = Bit_Shift_out1[1];

  assign Sum_out1 = Bit_Shift_out1_0 + Bit_Shift_out1_1;
  assign Out1 = Sum_out1;

endmodule  // Audio_Filter_IP_src_Data_Type_Conversion_In

